[[2023.01.1]]
lang = "Rust"
name = "Naive"
desc = "A somewhat simple, iterator-based solution"

path = "solutions/2023/Rust/d1p1_naive"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release'
exec = "./target/release/d1p1_naive"
clean = "cargo clean"
