[[2023.01.1]]
lang = "Rust"
name = "Naive"
desc = "A somewhat simple, iterator-based solution"

path = "solutions/2023/Rust/d1p1_naive"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../target/release/d1p1_naive"
clean = "cargo clean"

[[2023.01.1]]
lang = "Rust"
name = "Iterator"
desc = "An iterator-based solution"

path = "solutions/2023/Rust/d1p1_onepass"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../target/release/d1p1_onepass"
clean = "cargo clean"

[[2023.01.1]]
lang = "Rust"
name = "Manually vectorized"
desc = "An implementation specific to x86-64 using mostly branchless operations and operating on 32 bytes at a time."

path = "solutions/2023/Rust/d1p1_manual_simd"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../target/release/d1p1_manual_simd"
clean = "cargo clean"

[[2023.01.1]]
lang = "C"
name = "Naive"
desc = "Every second of writing this was excrutiating and I never want to do it again."

path = "solutions/2023/C/d1p1_basic"

build = 'make build'
exec = "./d1p1"
clean = "make clean"

[[2023.01.1]]
lang = "Scala"
name = "Basic Iterator Sln"
desc = "I threw it together relatively quickly"

path = "solutions/2023/Scala/Iter"
build = "sbt package"
exec = "if type 'scala3' &> /dev/null; then SCALA=scala3; else SCALA=scala; fi; $SCALA ./target/scala-3.4.0/aocone_3-0.jar"
shell = ["sh", "-c"]
clean = "sbt clean"

[[2023.01.1]]
lang = "Scala"
name = "IteratorNative"
desc = "Basic iterator solution but native this time"

path = "solutions/2023/Scala/iternative"

build = "sbt nativeLink"
exec = "./target/scala-3.3.1/iternative-out"
clean = "sbt clean"

[[2023.04.1]]
lang = "Rust"
name = "Basic"
desc = "A somewhat simple solution using parser combinators(winnow)"

path = "solutions/2023/Rust/d4p1"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../target/release/d4p1"
clean = "cargo clean"
